version: "3"

services:
    nodeserver:
        build: ./server
        volumes:
            - "./server/server:${PWD}/server"
        ports:
            - "8080:8080"
    frontend:
        build: ./web-client
        volumes:
            - "./web-client/web-client:/${PWD}web-client"
        ports:
            - "8081:8081"
