version: '2'
services:
  web:
    build: .
    command:
      - cd server
      - npm install
      - npm start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      NODE_ENV: developement
  postgres:
    image: postgres:9.6.2-alpine
